---
build-deb-packages:
  parallel:
    matrix:
      - OS: ubuntu
        CODENAME: jammy
      - OS: ubuntu
        CODENAME: noble
  stage: build
  image: ${OS}:${CODENAME}
  script:
    - ci/build_debs.sh ${CODENAME}
  artifacts:
    paths:
      - ./*.deb
